#index:
#    path: /
#    controller: App\Controller\DefaultController::index


auth:
    path: /auth
    controller: App\Controller\AutenticacionController::index

logout:
    path:     /logout/{usuario}
    controller: App\Controller\AutenticacionController::logout
    methods:  [GET]